# Generated by Django 4.2.30 on 2026-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name': '登录注册信息',
                'verbose_name_plural': '登录注册信息',
                'db_table': 'enter',
            },
        ),
    ]
