# Generated by Django 4.2.30 on 2026-06-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enter',
            options={'verbose_name': '注册表单', 'verbose_name_plural': '注册表单'},
        ),
    ]
